const UPDATE_USER_STATE = "UPDATE_USER_STATE";
const UPDATE_SIGN_UP_STATE = "UPDATE_SIGN_UP_STATE";
const UPDATE_PROFILE_STATE = "UPDATE_PROFILE_STATE";
const UPDATE_POOL_STATE = "UPDATE_POOL_STATE";
const UPDATE_PARAM_STATE = "UPDATE_PARAM_STATE";
const UPDATE_SKILL_STATE = "UPDATE_SKILL_STATE";
const SHOW_PROFILE_STATE = "SHOW_PROFILE_STATE";

const RESET_SIGN_UP_STATE = "RESET_SIGN_UP_STATE";
const RESET_USER_STATE = "RESET_USER_STATE";
const RESET_PROFILE_STATE = "RESET_PROFILE_STATE";
const RESET_PROFILE_POOL_STATE = "RESET_PROFILE_POOL_STATE";
const RESET_SEARCH_PARAMS = "RESET_SEARCH_PARAMS";

const TRIGGER_NOTIFICATION = "TRIGGER_NOTIFICATION";
const SHOW_SPINNER = "SHOW_SPINNER";
const HIDE_SPINNER = "HIDE_SPINNER";

export {
    UPDATE_USER_STATE,
    RESET_USER_STATE,
    UPDATE_SIGN_UP_STATE,
    RESET_SIGN_UP_STATE,
    RESET_PROFILE_POOL_STATE,
    RESET_PROFILE_STATE,
    RESET_SEARCH_PARAMS,
    TRIGGER_NOTIFICATION,
    UPDATE_PROFILE_STATE,
    UPDATE_POOL_STATE,
    UPDATE_PARAM_STATE,
    UPDATE_SKILL_STATE,
    SHOW_PROFILE_STATE,
    SHOW_SPINNER,
    HIDE_SPINNER
}